name: Push to npm lib-jle-pwd

on:
  push:
    branches:
      - main
    paths:
      - UI_Generic/workspace-jle-password/projects/lib-jle-pwd/**


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}