name: PullRequest Lib jle-pwd

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - UI_Generic/workspace-jle-password/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        working-directory: UI_Generic/workspace-jle-password
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build lib-jle-pwd
        working-directory: UI_Generic/workspace-jle-password
        run: |
          npm run build lib-jle-pwd
          
      - name: Build test app
        working-directory: UI_Generic/workspace-jle-password
        run: |
          npm run build test-app

      #- name: Test
      #  working-directory: UI_Generic/workspace-jle-password
      #  run: |
      #    npm test -- --watch=false --browsers=ChromeHeadless
      #  env:
      #    CI: true

